### ISSUE TITLE
Login e registrazione

### ISSUE THREAD

**Issue by Bittosan** [Bittosan/CounterShock#1]
Creare una classe di login e di registrazione usando un database sql che sfrutti le librerie interne di android studio. La libreria nello specifico è SQLiteDatabase.

**Comment by Bittosan** [comment]
Sarebbe meglio eliminare il fragment della registrazione e creare un nuovo layout contenente i dati per effettuarla perché android studio ogni tanto ci da problemi con i fragment.

**Comment by a-a-2491** [comment]
registrazione utente realizzata, riguardo il login è necessario la realizzazione di un sistema per fare in modo che l'accesso venga mantenuto

**Comment by a-a-2491** [comment]
questione risolta attraverso l'uso della classe SharedPreferences; ora l'utente manterrà l'accesso finché non effettuerà il logout. Se dopo il login l'utente chiuderà l'app, quest'ultima alla riapertura lo riporterà nella UserActivity e non nella schermata di benvenuto!
