### ISSUE TITLE
RoadActivity

### ISSUE THREAD

**Issue by a-a-2491** [Bittosan/CounterShock#2]
Realizzazione di un'attività che consenta di visualizzare una lista di percorsi, dove su ogni riga saranno visualizzati partenza e destinazione. Inoltre cliccando sulla una riga della lista, realizzare un evento che permetta all'utente di visualizzare i dettagli relativi ad un percorso (id percorso, partenza, arrivo, numero fossi e distanza in km).

**Comment by Bittosan** [comment]
La classe InsertRoadActivity ha bisogno della gestione di alcuni bug onde evitare il crash dell'applicazione.

**Comment by a-a-2491** [comment]
hai ragione, infatti mi sono appena accorto che se inserisci input di tipo diverso l'app si arresta; provvederò appena possibile.
