### ISSUE TITLE
Diagrammi uml

### ISSUE THREAD

**Issue by Bittosan** [Bittosan/CounterShock#3]
Rivedere diagrammi uml e renderli coerenti alle funzioni implementate.

**Comment by Bittosan** [comment]
Martedì mattina è prevista una riunione per discutere dei diagrammi uml e della programmazione effettuata. Successivamente si avvierà una fase di testing supportata da tool, suggerirei di usare Jacoco ed Espresso

**Comment by a-a-2491** [comment]
I diagrammi uml sono stati modificati e resi coerenti al materiale che abbiamo sviluppato ed è stata aggiornata anche la documentazione
