### ISSUE TITLE
Bug fix

### ISSUE THREAD

**Issue by a-a-2491** [Bittosan/CounterShock#5]
a fronte dei test black box iniziali effettuati, sorge la necessità di fixare bug relativi a pulsanti ( in particolar modo nel pulsante che attiva e disattiva l'accelerometro ) e le editText relative all'attività di inserimento di un percorso.

**Comment by Bittosan** [comment]
va bene, risolveremo i bug in questi giorni. Successivamente caricheremo su git la versione aggiornata del progetto.

**Comment by Bittosan** [comment]
Bug risolti, sarà caricata in questi giorni la versione aggiornata.

**Comment by a-a-2491** [comment]
bisogna gestire i casi in cui viene inserito input con il formato sbagliato, si deve fare in modo che l'app non vada in crash, provvedo io adesso!
